/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as CodingIndexRouteImport } from './routes/coding.index'
import { Route as CodingIdRouteImport } from './routes/coding.$id'
import { Route as RadarIndexRouteImport } from './routes/radar.index'
import { Route as RadarIdRouteImport } from './routes/radar.$id'
import { Route as ApiRadarIndexRouteImport } from './routes/api/radar.index'
import { Route as ApiRunsIndexRouteImport } from './routes/api/runs.index'
import { Route as ApiRunsIdRouteImport } from './routes/api/runs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingIndexRoute = CodingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodingRoute,
} as any)
const CodingIdRoute = CodingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CodingRoute,
} as any)
const RadarIndexRoute = RadarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RadarRoute,
} as any)
const RadarIdRoute = RadarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RadarRoute,
} as any)
const ApiRadarIndexRoute = ApiRadarIndexRouteImport.update({
  id: '/api/radar/',
  path: '/api/radar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIndexRoute = ApiRunsIndexRouteImport.update({
  id: '/api/runs/',
  path: '/api/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIdRoute = ApiRunsIdRouteImport.update({
  id: '/api/runs/$id',
  path: '/api/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coding': typeof CodingRouteWithChildren
  '/radar': typeof RadarRouteWithChildren
  '/coding/$id': typeof CodingIdRoute
  '/radar/$id': typeof RadarIdRoute
  '/coding/': typeof CodingIndexRoute
  '/radar/': typeof RadarIndexRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/radar/': typeof ApiRadarIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coding/$id': typeof CodingIdRoute
  '/radar/$id': typeof RadarIdRoute
  '/coding': typeof CodingIndexRoute
  '/radar': typeof RadarIndexRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/radar': typeof ApiRadarIndexRoute
  '/api/runs': typeof ApiRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coding': typeof CodingRouteWithChildren
  '/radar': typeof RadarRouteWithChildren
  '/coding/$id': typeof CodingIdRoute
  '/radar/$id': typeof RadarIdRoute
  '/coding/': typeof CodingIndexRoute
  '/radar/': typeof RadarIndexRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/radar/': typeof ApiRadarIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coding'
    | '/radar'
    | '/coding/$id'
    | '/radar/$id'
    | '/coding/'
    | '/radar/'
    | '/api/runs/$id'
    | '/api/radar/'
    | '/api/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coding/$id'
    | '/radar/$id'
    | '/coding'
    | '/radar'
    | '/api/runs/$id'
    | '/api/radar'
    | '/api/runs'
  id:
    | '__root__'
    | '/'
    | '/coding'
    | '/radar'
    | '/coding/$id'
    | '/radar/$id'
    | '/coding/'
    | '/radar/'
    | '/api/runs/$id'
    | '/api/radar/'
    | '/api/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodingRoute: typeof CodingRouteWithChildren
  RadarRoute: typeof RadarRouteWithChildren
  ApiRunsIdRoute: typeof ApiRunsIdRoute
  ApiRadarIndexRoute: typeof ApiRadarIndexRoute
  ApiRunsIndexRoute: typeof ApiRunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding/': {
      id: '/coding/'
      path: '/'
      fullPath: '/coding/'
      preLoaderRoute: typeof CodingIndexRouteImport
      parentRoute: typeof CodingRoute
    }
    '/coding/$id': {
      id: '/coding/$id'
      path: '/$id'
      fullPath: '/coding/$id'
      preLoaderRoute: typeof CodingIdRouteImport
      parentRoute: typeof CodingRoute
    }
    '/radar/': {
      id: '/radar/'
      path: '/'
      fullPath: '/radar/'
      preLoaderRoute: typeof RadarIndexRouteImport
      parentRoute: typeof RadarRoute
    }
    '/radar/$id': {
      id: '/radar/$id'
      path: '/$id'
      fullPath: '/radar/$id'
      preLoaderRoute: typeof RadarIdRouteImport
      parentRoute: typeof RadarRoute
    }
    '/api/radar/': {
      id: '/api/radar/'
      path: '/api/radar'
      fullPath: '/api/radar/'
      preLoaderRoute: typeof ApiRadarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/': {
      id: '/api/runs/'
      path: '/api/runs'
      fullPath: '/api/runs/'
      preLoaderRoute: typeof ApiRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$id': {
      id: '/api/runs/$id'
      path: '/api/runs/$id'
      fullPath: '/api/runs/$id'
      preLoaderRoute: typeof ApiRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CodingRouteChildren {
  CodingIdRoute: typeof CodingIdRoute
  CodingIndexRoute: typeof CodingIndexRoute
}

const CodingRouteChildren: CodingRouteChildren = {
  CodingIdRoute: CodingIdRoute,
  CodingIndexRoute: CodingIndexRoute,
}

const CodingRouteWithChildren =
  CodingRoute._addFileChildren(CodingRouteChildren)

interface RadarRouteChildren {
  RadarIdRoute: typeof RadarIdRoute
  RadarIndexRoute: typeof RadarIndexRoute
}

const RadarRouteChildren: RadarRouteChildren = {
  RadarIdRoute: RadarIdRoute,
  RadarIndexRoute: RadarIndexRoute,
}

const RadarRouteWithChildren = RadarRoute._addFileChildren(RadarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodingRoute: CodingRouteWithChildren,
  RadarRoute: RadarRouteWithChildren,
  ApiRunsIdRoute: ApiRunsIdRoute,
  ApiRadarIndexRoute: ApiRadarIndexRoute,
  ApiRunsIndexRoute: ApiRunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
