/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RawIdRouteImport } from './routes/raw.$id'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as ApiRunsIndexRouteImport } from './routes/api/runs.index'
import { Route as ApiRunsIdRouteImport } from './routes/api/runs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RawIdRoute = RawIdRouteImport.update({
  id: '/raw/$id',
  path: '/raw/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIndexRoute = ApiRunsIndexRouteImport.update({
  id: '/api/runs/',
  path: '/api/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIdRoute = ApiRunsIdRouteImport.update({
  id: '/api/runs/$id',
  path: '/api/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raw/$id': typeof RawIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/runs/': typeof ApiRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raw/$id': typeof RawIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/runs': typeof ApiRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/raw/$id': typeof RawIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/api/runs/$id': typeof ApiRunsIdRoute
  '/api/runs/': typeof ApiRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/raw/$id' | '/runs/$id' | '/api/runs/$id' | '/api/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raw/$id' | '/runs/$id' | '/api/runs/$id' | '/api/runs'
  id:
    '__root__' | '/' | '/raw/$id' | '/runs/$id' | '/api/runs/$id' | '/api/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RawIdRoute: typeof RawIdRoute
  RunsIdRoute: typeof RunsIdRoute
  ApiRunsIdRoute: typeof ApiRunsIdRoute
  ApiRunsIndexRoute: typeof ApiRunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$id': {
      id: '/raw/$id'
      path: '/raw/$id'
      fullPath: '/raw/$id'
      preLoaderRoute: typeof RawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/': {
      id: '/api/runs/'
      path: '/api/runs'
      fullPath: '/api/runs/'
      preLoaderRoute: typeof ApiRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$id': {
      id: '/api/runs/$id'
      path: '/api/runs/$id'
      fullPath: '/api/runs/$id'
      preLoaderRoute: typeof ApiRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RawIdRoute: RawIdRoute,
  RunsIdRoute: RunsIdRoute,
  ApiRunsIdRoute: ApiRunsIdRoute,
  ApiRunsIndexRoute: ApiRunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
